---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  StyleGuideBaseURL: https://rubystyle.guide
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Layout/IndentationStyle:
  IndentationWidth: 2

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - context
    - define
    - describe
    - factory
    - group
    - shared_examples

Metrics/ClassLength:
  Max: 320

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Exclude:
    - Guardfile

Naming/PredicateName:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - and
    - as
    - for
    - when
    - with
    - without

RSpec/ExampleLength:
  Max: 13

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - spec/factories/*.rb
  AllowedMethods:
    - html
    - let
    - let!
    - sequence
    - subject
    - watch

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: format

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - desc

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/StringLiterals:
  EnforcedStyle: double_quotes
